[[redirects]]
  from = "/admin"
  to = "https://online-resources-inc-studio.netlify.app/"
  status = 301
  force = true
  
# Rewrite a path
[[redirects]]
  from = "/foundry"
  to = "/industries/casting-and-foundry"
  status = 302
